id: nl.nuts.anw
status: draft
version: 0.1.0
fhirVersion: 4.0.1

canonical: http://nuts-foundation.github.io/nl-generic-anw-ig
name: NLAnwIG
title: Netherlands - ANW implementation guide
language: en-US

copyrightYear: 2025+
releaseLabel: ci-build

license: GPL-3.0-or-later # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: urn:iso:std:iso:3166#NL "Netherlands" # https://www.hl7.org/fhir/valueset-jurisdiction.html

publisher:
  name: Stichting Nuts
  url: https://www.nuts.nl

parameters:
  apply-version: false  # Prevent overwriting resource-specific versions
  default-version: true # Use IG version as fallback for resources without explicit version

menu:
  Home: index.html
  Documentation:
    Technical Documentation v1: technical-documentation-v1.html
  Artifacts: artifacts.html